import { expect, test, type Locator, type Page } from '@playwright/test'

async function dragOutside(page: Page, modal: Locator) {
  const box = (await modal.boundingBox())!
  await page.mouse.move(box.x + 30, box.y + 30)
  await page.mouse.down()
  await page.mouse.move(5, 5)
  await page.mouse.up()
  await expect(modal).toBeVisible()
}

test('only a full backdrop click dismisses the main dialog', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /新建账本/ }).click()
  const modal = page.locator('.modal')
  await expect(page.locator('.modal-motion-enter-active')).toHaveCount(0)
  await dragOutside(page, modal)
  const box = (await modal.boundingBox())!
  await page.mouse.move(5, 5)
  await page.mouse.down()
  await page.mouse.move(box.x + 30, box.y + 30)
  await page.mouse.up()
  await expect(modal).toBeVisible()
  await page.mouse.click(5, 5)
  await expect(modal).not.toBeVisible()
})

test('appearance survives away, exit and reload; selecting locked ledgers and creating use their themes', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /新建账本/ }).click()
  await page.getByLabel('账本名称').fill('主题记忆账本')
  await page.getByLabel('访问口令', { exact: true }).fill('test-passphrase')
  await page.getByLabel('确认口令').fill('test-passphrase')
  await page.getByRole('button', { name: '创建并进入' }).click()
  await page.locator('nav button').filter({ hasText: '设置' }).click()
  await page.locator('.theme-entry').click()
  await page.getByLabel('色相角度').fill('150')
  await page.getByRole('button', { name: '保存到当前账本' }).click()
  await expect(page.locator('.theme-modal')).not.toBeVisible()
  const toggle = page.getByRole('checkbox', { name: '切换亮暗色调' })
  await expect(toggle).toBeEnabled()
  await page.locator('.tone-switch').click()
  await expect(toggle).toBeChecked()
  await expect(toggle).toBeEnabled()
  await page.getByRole('button', { name: /暂离/ }).click()
  await expect(page.locator('.app-shell')).not.toBeVisible()
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-color-tone', 'dark')
  await expect(page.locator('html')).toHaveCSS('--theme-primary-hue', '150')
  await page.locator('.ledger-panel').evaluate(async element => {
    await Promise.all(element.getAnimations({ subtree: true }).map(animation => animation.finished.catch(() => {})))
  })
  await page.screenshot({ path: test.info().outputPath('remembered-dark-login.png'), fullPage: true })
  await page.getByRole('button', { name: /新建账本/ }).click()
  await expect(page.locator('html')).toHaveCSS('--theme-primary-hue', '270')
  await expect(page.locator('html')).toHaveAttribute('data-color-tone', 'light')
  await page.getByRole('button', { name: '关闭对话框' }).click()
  await page.locator('.ledger-card').filter({ hasText: '主题记忆账本' }).click()
  await expect(page.locator('html')).toHaveCSS('--theme-primary-hue', '150')
  await expect(page.locator('html')).toHaveAttribute('data-color-tone', 'dark')
  await page.getByLabel('访问口令').fill('test-passphrase')
  await page.getByRole('button', { name: '解锁账本', exact: true }).click()
  await expect(page.locator('.welcome')).toBeVisible()
  await expect(page.locator('.login-shell')).toHaveCount(0)
  await expect(page.locator('.app-entering')).toHaveCount(0)
  await page.screenshot({ path: test.info().outputPath('textured-dashboard.png'), fullPage: true })
  await page.locator('nav button').filter({ hasText: '统计' }).click()
  await page.getByRole('button', { name: '导出统计 PNG' }).click()
  await expect(page.locator('.modal-motion-enter-active')).toHaveCount(0)
  await dragOutside(page, page.locator('.export-modal'))
  await page.mouse.click(5, 5)
  await expect(page.locator('.export-modal')).not.toBeVisible()
  await page.getByRole('button', { name: /退出/ }).click()
  await expect(page.locator('.app-shell')).not.toBeVisible()
  await page.reload()
  await expect(page.locator('html')).toHaveCSS('--theme-primary-hue', '150')
})
