import { expect, test } from '@playwright/test'

test('advanced creation and independent account/tag pickers preserve entry layout', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /新建账本/ }).click()
  await expect(page.getByLabel('密钥派生算法')).not.toBeVisible()
  await page.getByRole('button', { name: /高级设置/ }).click()
  await page.getByLabel('密钥派生算法').selectOption('PBKDF2-SHA-512')
  await page.getByLabel('账本名称').fill('布局测试')
  await page.getByLabel('访问口令', { exact: true }).fill('test-passphrase')
  await page.getByLabel('确认口令').fill('test-passphrase')
  await page.getByRole('button', { name: '创建并进入' }).click()
  await expect(page.getByText('资金总览')).toBeVisible({ timeout: 15000 })
  await page.locator('nav button').filter({ hasText: '账户' }).click()
  await expect(page.getByPlaceholder('例如：日常银行卡')).not.toBeVisible()
  await page.getByRole('button', { name: /添加账户/ }).click()
  await page.getByPlaceholder('例如：日常银行卡').fill('日常账户')
  await page.getByRole('button', { name: '保存账户' }).click()
  await expect(page.getByRole('heading', { name: '日常账户' })).toBeVisible()
  await page.locator('nav button').filter({ hasText: '总览' }).click()
  await page.getByRole('button', { name: /记录一笔/ }).click()
  const date = page.getByLabel('日期', { exact: true })
  await expect(page.locator('.modal-motion-enter-active')).toHaveCount(0)
  await expect(page.locator('.dialog-step-enter-active')).toHaveCount(0)
  const layout = () => date.evaluate(element => {
    const rect = element.getBoundingClientRect(), form = element.closest('.transaction-form')!.getBoundingClientRect()
    return { x: rect.x - form.x, y: rect.y - form.y, width: rect.width, height: rect.height }
  })
  const before = await layout()
  await page.getByRole('button', { name: '选择支出账户' }).click()
  await page.getByRole('dialog', { name: '选择支出账户' }).getByRole('button', { name: '日常账户' }).click()
  await expect(page.getByRole('dialog', { name: '选择支出账户' })).not.toBeVisible()
  expect(await layout()).toEqual(before)
  await page.getByRole('button', { name: '选择标签', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '选择标签' })).toBeVisible()
  await page.getByRole('dialog', { name: '选择标签' }).getByRole('button', { name: '取消', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '选择标签' })).not.toBeVisible()
  expect(await layout()).toEqual(before)
  await page.screenshot({ path: 'test-results/entry-layout.png', fullPage: true })
})
