import { expect, test } from '@playwright/test'

test('advanced creation and independent account/tag pickers preserve entry layout', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /新建账本/ }).click()
  await expect(page.getByLabel('密钥派生算法')).not.toBeVisible()
  await expect(page.locator('.advanced-trigger .disclosure-triangle')).toHaveCount(1)
  await page.getByRole('button', { name: /高级设置/ }).click()
  await expect(page.locator('.advanced-trigger .disclosure-triangle')).toHaveClass(/expanded/)
  await page.getByLabel('密钥派生算法').selectOption('PBKDF2-SHA-512')
  await page.getByLabel('账本名称').fill('布局测试')
  await page.getByLabel('访问口令', { exact: true }).fill('test-passphrase')
  await page.getByLabel('确认口令').fill('test-passphrase')
  await page.getByRole('button', { name: '创建并进入' }).click()
  await expect(page.getByText('资金总览')).toBeVisible({ timeout: 15000 })
  await page.locator('nav button').filter({ hasText: '账户' }).click()
  await expect(page.getByPlaceholder('例如：日常银行卡')).not.toBeVisible()
  await page.getByRole('button', { name: /添加账户/ }).click()
  await page.getByPlaceholder('例如：日常银行卡').fill('日常账户')
  await page.locator('[name="account-form-initial-currency"]').first().fill('100')
  const saveAccount = page.getByRole('button', { name: '保存账户' })
  await expect(saveAccount).toBeEnabled({ timeout: 15000 })
  await saveAccount.click()
  await expect(page.getByRole('heading', { name: '日常账户' })).toBeVisible()
  await page.locator('nav button').filter({ hasText: '总览' }).click()
  await page.getByRole('button', { name: /记录一笔/ }).click()
  await expect(page.locator('.account-picker-trigger .disclosure-triangle')).toHaveCount(1)
  const date = page.getByLabel('日期', { exact: true })
  await expect(page.locator('.modal-motion-enter-active')).toHaveCount(0)
  await expect(page.locator('.dialog-step-enter-active')).toHaveCount(0)
  const layout = () => date.evaluate(element => {
    const rect = element.getBoundingClientRect(), form = element.closest('.transaction-form')!.getBoundingClientRect()
    return { x: rect.x - form.x, y: rect.y - form.y, width: rect.width, height: rect.height }
  })
  const before = await layout()
  await page.getByRole('button', { name: '选择支出账户' }).click()
  await page.getByRole('dialog', { name: '选择支出账户' }).getByRole('button', { name: '日常账户' }).click()
  await expect(page.getByRole('dialog', { name: '选择支出账户' })).not.toBeVisible()
  expect(await layout()).toEqual(before)
  await page.getByRole('button', { name: '选择标签', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '选择标签' })).toBeVisible()
  await page.getByRole('dialog', { name: '选择标签' }).getByRole('button', { name: '取消', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '选择标签' })).not.toBeVisible()
  expect(await layout()).toEqual(before)
  await page.locator('[name="draft-form-source-amount"]').fill('1')
  await page.getByRole('button', { name: '选择标签', exact: true }).click()
  await page.getByRole('dialog', { name: '选择标签' }).locator('.tag').filter({ hasText: '饮食' }).click()
  await page.getByRole('dialog', { name: '选择标签' }).getByRole('button', { name: '确认', exact: true }).click()
  await page.getByRole('button', { name: '加入待提交列表' }).click()
  await page.getByRole('button', { name: '选择支出账户' }).click()
  await page.getByRole('dialog', { name: '选择支出账户' }).getByRole('button', { name: '日常账户' }).click()
  await page.locator('[name="draft-form-source-amount"]').fill('2')
  await page.getByRole('button', { name: '选择标签', exact: true }).click()
  await page.getByRole('dialog', { name: '选择标签' }).locator('.tag').filter({ hasText: '出行' }).click()
  await page.getByRole('dialog', { name: '选择标签' }).getByRole('button', { name: '确认', exact: true }).click()
  await page.getByRole('button', { name: '直接提交', exact: true }).click()
  await expect(page.locator('.modal')).toHaveCount(0)
  await page.locator('nav button').filter({ hasText: '账目' }).click()
  await expect(page.getByRole('heading', { name: '有效账目 · 2 条' })).toBeVisible()
  await page.locator('.transaction-list article').first().getByRole('button', { name: /删除账目/ }).click()
  const deleteDialog = page.getByRole('dialog', { name: '删除这笔账目？' })
  await deleteDialog.getByRole('button', { name: '确认删除账目' }).click()
  await expect(deleteDialog).not.toBeVisible()
  await expect(page.getByRole('heading', { name: '有效账目 · 1 条' })).toBeVisible()
  await expect(page.getByRole('button', { name: '已删除 (1)' })).toBeVisible()
  await page.screenshot({ path: 'test-results/entry-layout.png', fullPage: true })
})
