import { expect, test } from '@playwright/test'

test('advanced creation and independent account/tag pickers preserve entry layout', async ({ page }) => {
  test.setTimeout(60_000)
  await page.goto('/')
  await page.getByRole('button', { name: /新建账本/ }).click()
  await expect(page.getByLabel('密钥派生算法')).not.toBeVisible()
  const advancedTriangle = page.locator('.advanced-trigger .disclosure-triangle')
  await expect(advancedTriangle).toHaveCount(1)
  expect(await advancedTriangle.evaluate(icon => {
    const iconBox = icon.getBoundingClientRect(), buttonBox = icon.closest('button')!.getBoundingClientRect()
    return Math.abs(iconBox.top + iconBox.height / 2 - buttonBox.top - buttonBox.height / 2)
  })).toBeLessThan(1)
  await page.getByRole('button', { name: /高级设置/ }).click()
  await expect(page.locator('.advanced-trigger .disclosure-triangle')).toHaveClass(/expanded/)
  expect(await page.getByLabel('密钥派生算法').evaluate(select => !CSS.supports('appearance', 'base-select') || getComputedStyle(select, '::picker-icon').alignSelf === 'center')).toBe(true)
  await page.getByLabel('密钥派生算法').selectOption('PBKDF2-SHA-512')
  await page.getByLabel('账本名称').fill('布局测试')
  await page.getByLabel('访问口令', { exact: true }).fill('test-passphrase')
  await page.getByLabel('确认口令').fill('test-passphrase')
  await page.getByRole('button', { name: '创建并进入' }).click()
  await expect(page.getByText('资金总览')).toBeVisible({ timeout: 15000 })
  await page.locator('nav button').filter({ hasText: '账户' }).click()
  await expect(page.getByPlaceholder('例如：日常银行卡')).not.toBeVisible()
  await page.getByRole('button', { name: /添加账户/ }).click()
  await page.getByPlaceholder('例如：日常银行卡').fill('日常账户')
  await page.locator('[name="account-form-initial-currency"]').first().fill('100')
  const saveAccount = page.getByRole('button', { name: '保存账户' })
  await expect(saveAccount).toBeEnabled({ timeout: 15000 })
  await saveAccount.click()
  await expect(page.getByRole('heading', { name: '日常账户' })).toBeVisible()
  const accountSearch = page.getByPlaceholder('搜索账户名称')
  await accountSearch.fill('不存在')
  await expect(page.getByText('没有符合筛选条件的账户')).toBeVisible()
  await accountSearch.fill('日常')
  await expect(page.getByRole('heading', { name: '日常账户' })).toBeVisible()
  await page.locator('[name="account-status-filter"]').selectOption('deleted')
  await expect(page.getByText('没有符合筛选条件的账户')).toBeVisible()
  await page.locator('[name="account-status-filter"]').selectOption('active')
  await expect(page.getByRole('heading', { name: '日常账户' })).toBeVisible()
  await page.locator('nav button').filter({ hasText: '总览' }).click()
  await page.getByRole('button', { name: /记录一笔/ }).click()
  await expect(page.locator('.account-picker-trigger .disclosure-triangle')).toHaveCount(1)
  const date = page.getByLabel('发生时间', { exact: true })
  await expect(page.locator('.modal-motion-enter-active')).toHaveCount(0)
  await expect(page.locator('.dialog-step-enter-active')).toHaveCount(0)
  const layout = () => date.evaluate(element => {
    const rect = element.getBoundingClientRect(), form = element.closest('.transaction-form')!.getBoundingClientRect()
    return { x: rect.x - form.x, y: rect.y - form.y, width: rect.width, height: rect.height }
  })
  const before = await layout()
  await page.getByRole('button', { name: '选择支出账户' }).click()
  await page.getByRole('dialog', { name: '选择支出账户' }).getByRole('button', { name: '日常账户' }).click()
  await expect(page.getByRole('dialog', { name: '选择支出账户' })).not.toBeVisible()
  expect(await layout()).toEqual(before)
  const expenseRow = await page.locator('.transaction-form').evaluate(form => {
    const boxes = ['.entry-date','.entry-source-account','.entry-source-amount'].map(selector => form.querySelector(selector)!.getBoundingClientRect())
    return boxes.map(box => ({ left: box.left, right: box.right, top: box.top, bottom: box.bottom }))
  })
  if (page.viewportSize()!.width > 760) {
    expect(Math.max(...expenseRow.map(box => box.top)) - Math.min(...expenseRow.map(box => box.top))).toBeLessThan(2)
    expect(expenseRow[0]!.right).toBeLessThanOrEqual(expenseRow[1]!.left)
  }
  await page.locator('[name="draft-form-kind"]').selectOption('income')
  const incomeRow = await page.locator('.transaction-form').evaluate(form => {
    const boxes = ['.entry-date','.entry-destination-account','.entry-destination-amount'].map(selector => form.querySelector(selector)!.getBoundingClientRect())
    return boxes.map(box => ({ left: box.left, right: box.right, top: box.top }))
  })
  if (page.viewportSize()!.width > 760) {
    expect(Math.max(...incomeRow.map(box => box.top)) - Math.min(...incomeRow.map(box => box.top))).toBeLessThan(2)
    expect(incomeRow[0]!.right).toBeLessThanOrEqual(incomeRow[1]!.left)
  }
  await page.locator('[name="draft-form-kind"]').selectOption('expense')
  await page.getByRole('button', { name: '选择标签', exact: true }).click()
  const initialTagPicker = page.getByRole('dialog', { name: '选择标签' })
  await expect(initialTagPicker).toBeVisible()
  const teleportedTagStyle = await initialTagPicker.locator('.tag-selection .tag-chip').first().evaluate((tag) => {
    const style = getComputedStyle(tag)
    return { borderStyle: style.borderTopStyle, borderRadius: style.borderRadius, horizontalPadding: Number.parseFloat(style.paddingLeft), backgroundColor: style.backgroundColor }
  })
  expect(teleportedTagStyle.borderStyle).toBe('solid')
  expect(teleportedTagStyle.borderRadius).toBe('999px')
  expect(teleportedTagStyle.horizontalPadding).toBeGreaterThan(0)
  expect(teleportedTagStyle.backgroundColor).not.toBe('rgba(0, 0, 0, 0)')
  await initialTagPicker.getByRole('button', { name: '取消', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '选择标签' })).not.toBeVisible()
  expect(await layout()).toEqual(before)
  await page.locator('[name="draft-form-source-amount"]').fill('1')
  await date.fill('2026-09-11T18:00')
  await page.locator('[name="draft-form-note"]').fill('批次第一条')
  await page.getByRole('button', { name: '选择标签', exact: true }).click()
  await page.getByRole('dialog', { name: '选择标签' }).locator('.tag-selection .tag-chip').filter({ hasText: '饮食' }).click()
  await page.getByRole('dialog', { name: '选择标签' }).getByRole('button', { name: '确认', exact: true }).click()
  await page.getByRole('button', { name: '加入待提交列表' }).click()
  await page.getByRole('button', { name: '选择支出账户' }).click()
  await page.getByRole('dialog', { name: '选择支出账户' }).getByRole('button', { name: '日常账户' }).click()
  await page.locator('[name="draft-form-source-amount"]').fill('2')
  await page.getByLabel('发生时间', { exact: true }).fill('2026-09-11T20:00')
  await page.locator('[name="draft-form-note"]').fill('批次第二条')
  await page.getByRole('button', { name: '选择标签', exact: true }).click()
  await page.getByRole('dialog', { name: '选择标签' }).locator('.tag-selection .tag-chip').filter({ hasText: '出行' }).click()
  await page.getByRole('dialog', { name: '选择标签' }).getByRole('button', { name: '确认', exact: true }).click()
  await page.getByRole('button', { name: '加入待提交列表' }).click()
  const pendingRows = page.locator('.pending-list > div')
  await expect(pendingRows).toHaveCount(2)
  await expect(pendingRows.nth(0)).toContainText('18:00:00')
  await expect(pendingRows.nth(1)).toContainText('20:00:00')
  await pendingRows.nth(0).locator('.drag-handle').focus()
  await page.keyboard.press('ArrowDown')
  await expect(pendingRows.nth(0)).toContainText('20:00:00')
  await expect(pendingRows.nth(1)).toContainText('18:00:00')
  await page.getByRole('button', { name: '直接提交', exact: true }).click()
  await expect(page.locator('.modal')).toHaveCount(0)
  await page.locator('nav button').filter({ hasText: '账目' }).click()
  await expect(page.getByRole('heading', { name: '有效账目 · 2 条' })).toBeVisible()
  // Reordering exchanges the two staging-time slots. The first draft now owns the
  // later slot and therefore appears first under "最近修改优先".
  await expect(page.locator('.transaction-list article').nth(0)).toContainText('批次第一条')
  await expect(page.locator('.transaction-list article').nth(1)).toContainText('批次第二条')
  await page.locator('[name="transaction-filters-sort"]').selectOption('booked-desc')
  await expect(page.locator('.transaction-list article').nth(0)).toContainText('批次第二条')
  await expect(page.locator('.transaction-list article').nth(1)).toContainText('批次第一条')
  await page.locator('.transaction-list article').first().getByRole('button', { name: /删除账目/ }).click()
  const deleteDialog = page.getByRole('dialog', { name: '删除这笔账目？' })
  await deleteDialog.getByRole('button', { name: '确认删除账目' }).click()
  await expect(deleteDialog).not.toBeVisible()
  await expect(page.getByRole('heading', { name: '有效账目 · 1 条' })).toBeVisible()
  await expect(page.getByRole('button', { name: '已删除 (1)' })).toBeVisible()
  await page.locator('.app-content').getByRole('button', { name: '＋ 新增账目', exact: true }).click()
  await page.locator('[name="draft-form-kind"]').selectOption('income')
  await page.getByRole('button', { name: '选择收入账户', exact: true }).click()
  await page.getByRole('dialog', { name: '选择收入账户' }).getByRole('button', { name: '日常账户', exact: true }).click()
  await page.locator('[name="draft-form-destination-amount"]').fill('3')
  await page.getByRole('button', { name: '选择标签', exact: true }).click()
  const incomePicker = page.getByRole('dialog', { name: '选择标签' })
  await expect(incomePicker.locator('[name="tag-parent-category"]')).toBeDisabled()
  await expect(incomePicker.locator('.tag-selection')).toContainText('其他收入')
  await expect(incomePicker.locator('.tag-selection')).not.toContainText('饮食')
  await incomePicker.locator('.tag-selection').getByRole('button', { name: '其他收入', exact: true }).click()
  await incomePicker.getByRole('button', { name: '确认', exact: true }).click()
  await page.getByRole('button', { name: '直接提交', exact: true }).click()
  await expect(page.locator('.modal')).toHaveCount(0)
  await page.screenshot({ path: 'test-results/entry-layout.png', fullPage: true })
})
