import { expect, test } from '@playwright/test'

test('cross-currency exchange is reported on both sides with implicit tags and chart axes', async ({ page }) => {
  test.setTimeout(60_000)
  await page.goto('/')
  await page.getByRole('button', { name: /新建账本/ }).click()
  await page.getByLabel('账本名称').fill('换汇统计测试')
  await page.getByLabel('访问口令', { exact: true }).fill('test-passphrase')
  await page.getByLabel('确认口令').fill('test-passphrase')
  await page.getByRole('button', { name: '创建并进入' }).click()

  await page.locator('nav button').filter({ hasText: '账户' }).click()
  await page.getByRole('button', { name: /添加账户/ }).click()
  await page.getByPlaceholder('例如：日常银行卡').fill('换汇钱包')
  await page.locator('[name="account-form-initial-currency"]').first().fill('500')
  await page.getByRole('button', { name: '保存账户' }).click()

  await page.locator('nav button').filter({ hasText: '总览' }).click()
  await page.getByRole('button', { name: /记录一笔/ }).click()
  await page.locator('[name="draft-form-kind"]').selectOption('transfer')
  await page.getByRole('button', { name: '选择支出账户' }).click()
  await page.getByRole('dialog', { name: '选择支出账户' }).getByRole('button', { name: '换汇钱包' }).click()
  await page.getByRole('button', { name: '选择收入账户' }).click()
  await page.getByRole('dialog', { name: '选择收入账户' }).getByRole('button', { name: '换汇钱包' }).click()
  await page.locator('[name="draft-form-destination-currency"]').selectOption('JPY')
  await page.locator('[name="draft-form-source-amount"]').fill('500')
  await page.locator('[name="draft-form-destination-amount"]').fill('10000')
  await page.getByRole('button', { name: '直接提交', exact: true }).click()

  await expect(page.locator('.metric-card').filter({ hasText: 'CNY' })).toContainText('支出 ¥500.00')
  await expect(page.locator('.metric-card').filter({ hasText: 'JPY' })).toContainText('收入 JP¥10,000')
  await expect(page.locator('.implicit-tag-summary').first()).toContainText('主标签：换汇')

  await page.locator('nav button').filter({ hasText: '统计' }).click()
  await expect(page.locator('.line-chart .chart-axis')).toHaveCount(2)
  await expect(page.locator('.line-chart .chart-axis line')).toHaveCount(6)
  await expect(page.locator('.income-point')).toHaveCount(1)
  await expect(page.locator('.expense-point')).toHaveCount(1)
  await expect(page.locator('.exchange-point')).toHaveCount(1)
  const cashFlowChart = page.locator('.line-chart').first()
  const chartWidthRatio = await cashFlowChart.evaluate((chart) => chart.getBoundingClientRect().width / chart.parentElement!.getBoundingClientRect().width)
  expect(chartWidthRatio).toBeGreaterThan(.98)
  await expect(cashFlowChart.locator('.chart-axis text').first()).toHaveCSS('font-size', '12px')
  const cashFlowBox = (await cashFlowChart.boundingBox())!
  await cashFlowChart.hover({ position: { x: cashFlowBox.width * .2, y: cashFlowBox.height * .2 } })
  await expect(cashFlowChart.locator('.hover-guide')).toHaveCount(1)
  await expect(cashFlowChart.locator('.data-point.active')).toHaveCount(2)
  const cashFlowTooltip = cashFlowChart.locator('xpath=..').locator('.chart-tooltip')
  await expect(cashFlowTooltip).toContainText('收入')
  const firstTooltipBox = (await cashFlowTooltip.boundingBox())!
  await cashFlowChart.hover({ position: { x: cashFlowBox.width * .35, y: cashFlowBox.height * .35 } })
  const movedTooltipBox = (await cashFlowTooltip.boundingBox())!
  expect(movedTooltipBox.x - firstTooltipBox.x).toBeGreaterThan(cashFlowBox.width * .1)
  expect(movedTooltipBox.y - firstTooltipBox.y).toBeGreaterThan(cashFlowBox.height * .1)
  const donutSlice = page.locator('.donut-slice').first()
  const donutChart = page.locator('.donut-chart')
  const donutBox = (await donutChart.boundingBox())!
  await donutChart.hover({ position: { x: donutBox.width * .3, y: donutBox.height * .3 } })
  await expect(donutSlice).toHaveClass(/hovered/)
  const donutTooltip = page.locator('.donut-tooltip')
  await expect(donutTooltip).toContainText('换汇')
  await expect(donutTooltip).toContainText('100.0%')
  const firstDonutTooltipPosition = await donutTooltip.evaluate((element) => ({ left: Number.parseFloat((element as HTMLElement).style.left), top: Number.parseFloat((element as HTMLElement).style.top) }))
  await donutChart.hover({ position: { x: donutBox.width * .7, y: donutBox.height * .7 } })
  const movedDonutTooltipPosition = await donutTooltip.evaluate((element) => ({ left: Number.parseFloat((element as HTMLElement).style.left), top: Number.parseFloat((element as HTMLElement).style.top) }))
  expect(movedDonutTooltipPosition.left - firstDonutTooltipPosition.left).toBeGreaterThan(donutBox.width * .3)
  expect(movedDonutTooltipPosition.top - firstDonutTooltipPosition.top).toBeGreaterThan(donutBox.height * .3)
  const tooltipBackground = await donutTooltip.evaluate((element) => getComputedStyle(element).backgroundColor)
  expect(tooltipBackground).toMatch(/rgba\([^,]+,[^,]+,[^,]+,\s*0\.66\)/)
  const exchangeChart = page.locator('.line-chart.exchange')
  await exchangeChart.hover({ position: { x: 300, y: 100 } })
  await expect(exchangeChart.locator('xpath=..').locator('.chart-tooltip')).toContainText('CNY/JPY')
  const exchangeTableTrigger = page.getByText('查看换汇资金流与等价数据')
  await exchangeTableTrigger.focus()
  await page.keyboard.press('Enter')
  const exchangeTable = page.getByRole('table').last()
  await expect(exchangeTable).toContainText('兑换到日元')
  await expect(exchangeTable).toContainText('从人民币兑换')
  await expect(exchangeTable).toContainText('换汇')
  await page.setViewportSize({ width: 375, height: 760 })
  const tableOverflow = await exchangeTable.locator('xpath=..').evaluate((region) => ({
    clientWidth: region.clientWidth,
    scrollWidth: region.scrollWidth,
    pageOverflow: document.documentElement.scrollWidth - document.documentElement.clientWidth,
  }))
  expect(tableOverflow.scrollWidth).toBeGreaterThan(tableOverflow.clientWidth)
  expect(tableOverflow.pageOverflow).toBeLessThanOrEqual(1)
  await page.screenshot({ path: test.info().outputPath('exchange-statistics.png'), fullPage: true })
})
