import { expect, test } from '@playwright/test'

test('cross-currency exchange is reported on both sides with implicit tags and chart axes', async ({ page }) => {
  test.setTimeout(60_000)
  await page.goto('/')
  await page.getByRole('button', { name: /新建账本/ }).click()
  await page.getByLabel('账本名称').fill('换汇统计测试')
  await page.getByLabel('访问口令', { exact: true }).fill('test-passphrase')
  await page.getByLabel('确认口令').fill('test-passphrase')
  await page.getByRole('button', { name: '创建并进入' }).click()

  await page.locator('nav button').filter({ hasText: '账户' }).click()
  await page.getByRole('button', { name: /添加账户/ }).click()
  await page.getByPlaceholder('例如：日常银行卡').fill('换汇钱包')
  await page.locator('[name="account-form-initial-currency"]').first().fill('500')
  await page.getByRole('button', { name: '保存账户' }).click()

  await page.locator('nav button').filter({ hasText: '总览' }).click()
  await page.getByRole('button', { name: /记录一笔/ }).click()
  await page.locator('[name="draft-form-kind"]').selectOption('transfer')
  await page.getByRole('button', { name: '选择支出账户' }).click()
  await page.getByRole('dialog', { name: '选择支出账户' }).getByRole('button', { name: '换汇钱包' }).click()
  await page.getByRole('button', { name: '选择收入账户' }).click()
  await page.getByRole('dialog', { name: '选择收入账户' }).getByRole('button', { name: '换汇钱包' }).click()
  await page.locator('[name="draft-form-destination-currency"]').selectOption('JPY')
  await page.locator('[name="draft-form-source-amount"]').fill('500')
  await page.locator('[name="draft-form-destination-amount"]').fill('10000')
  await page.getByRole('button', { name: '直接提交', exact: true }).click()

  await expect(page.locator('.metric-card').filter({ hasText: 'CNY' })).toContainText('支出 ¥500.00')
  await expect(page.locator('.metric-card').filter({ hasText: 'JPY' })).toContainText('收入 JP¥10,000')
  await expect(page.locator('.implicit-tag-summary').first()).toContainText('主标签：换汇')

  await page.locator('nav button').filter({ hasText: '统计' }).click()
  await expect(page.locator('.line-chart .chart-axis')).toHaveCount(2)
  await expect(page.locator('.line-chart .chart-axis line')).toHaveCount(6)
  await expect(page.locator('.income-point')).toHaveCount(1)
  await expect(page.locator('.expense-point')).toHaveCount(1)
  await expect(page.locator('.exchange-point')).toHaveCount(1)
  await page.getByText('查看换汇资金流与等价数据').click()
  const exchangeTable = page.getByRole('table').last()
  await expect(exchangeTable).toContainText('兑换到日元')
  await expect(exchangeTable).toContainText('从人民币兑换')
  await expect(exchangeTable).toContainText('换汇')
  await page.screenshot({ path: test.info().outputPath('exchange-statistics.png'), fullPage: true })
})
