import { expect, test, type Page } from '@playwright/test'

async function seed(page: Page, legacy = false, save = true) {
  await page.goto('/')
  return page.evaluate(async ({ legacy, save }) => {
    const domainPath = '/src/core/domain/ledger.ts', cryptoPath = '/src/core/security/crypto.ts', repositoryPath = '/src/core/data/indexed-db/repository.ts'
    const domain = await import(/* @vite-ignore */ domainPath), security = await import(/* @vite-ignore */ cryptoPath), repository = await import(/* @vite-ignore */ repositoryPath)
    const ledger = domain.createLedger(legacy ? '旧版迁移测试' : '子标签测试')
    const account = domain.addAccount(ledger, '现金', false, { CNY: 10000 })
    if (legacy) {
      const tag = ledger.tags.find((item: { name: string }) => item.name === '饮食')
      domain.addTransactions(ledger, [{ kind: 'expense', sourceAccountId: account.id, sourceMoney: { currency: 'CNY', minorUnits: 100 }, selectedTagIds: [tag.id], primaryTagId: tag.id, bookedAt: '2026-09-08', occurredAt: '2026-09-08T18:00:00+08:00' }])
      ledger.schemaVersion = 1
      delete ledger.hierarchyChanges
      delete ledger.nextTransactionRevision
      ledger.transactions.forEach((tx: { explicitTagIds?: string[]; occurredAt?: string; timePrecision?: string; commitRevision?: number; commitIndex?: number; updatedRevision?: number }) => {
        delete tx.explicitTagIds
        delete tx.occurredAt
        delete tx.timePrecision
        delete tx.commitRevision
        delete tx.commitIndex
        delete tx.updatedRevision
      })
    }
    const container = await security.encryptLedger(ledger, 'test-passphrase')
    if (save) await repository.saveLedger(container, { ledgerId: ledger.id, displayName: ledger.name, normalizedName: ledger.name, containerVersion: 2, updatedAt: ledger.updatedAt })
    return { id: ledger.id, name: ledger.name, text: JSON.stringify(container) }
  }, { legacy, save })
}
async function unlock(page: Page, name: string) {
  await page.reload()
  await page.locator('.ledger-card').filter({ hasText: name }).click()
  await page.getByLabel('访问口令', { exact: true }).fill('test-passphrase')
  await page.getByRole('button', { name: '解锁账本', exact: true }).click()
}
async function addTag(page: Page, name: string, parent: string) {
  await page.locator('[name="tag-name"]').fill(name)
  await page.locator('[name="tag-parent-id"]').selectOption({ label: parent })
  await page.getByRole('button', { name: '添加', exact: true }).click()
  await expect(page.locator('.tag-management-list')).toContainText(name)
}
test('nested tag management, implicit selections, edit/correction and non-overlapping reporting', async ({ page }) => {
  test.setTimeout(90000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const fixture = await seed(page)
  await unlock(page, fixture.name)
  await page.locator('nav button').filter({ hasText: '标签' }).click()
  await addTag(page, '游戏付款', '娱乐')
  await addTag(page, '游戏内购买', '娱乐 › 游戏付款')
  await addTag(page, '电影', '娱乐')
  // A fresh session starts with every parent collapsed, then expands one level at a time.
  await page.reload()
  await page.locator('.ledger-card').filter({ hasText: fixture.name }).click()
  await page.getByLabel('访问口令', { exact: true }).fill('test-passphrase')
  await page.getByRole('button', { name: '解锁账本', exact: true }).click()
  await page.locator('nav button').filter({ hasText: '标签' }).click()
  // Collapsed descendants stay mounted so CSS can interpolate their height smoothly.
  await expect(page.locator('.tag-management-list article')).toHaveCount(8)
  await expect(page.locator('.tag-tree-collapse.open article')).toHaveCount(5)
  await expect(page.locator('.tag-tree-toggle .disclosure-triangle')).toHaveCount(2)
  await expect(page.locator('.tag-tree-toggle').first()).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  await expect(page.locator('.tag-tree-toggle').first()).toHaveCSS('border-radius', '0px')
  await page.locator('.tag-tree-collapse.open article').filter({ hasText: '娱乐' }).click()
  await expect(page.locator('.tag-tree-collapse.open article')).toHaveCount(7)
  await expect(page.locator('.tag-tree-collapse:not(.open) .tag-path', { hasText: '游戏内购买' })).toBeHidden()
  await page.locator('.tag-tree-collapse.open article').filter({ hasText: '游戏付款' }).click()
  const orderedNames = await page.locator('.tag-tree-collapse.open .tag-path').allTextContents()
  expect(orderedNames.indexOf('娱乐')).toBeLessThan(orderedNames.indexOf('游戏付款'))
  expect(orderedNames.indexOf('游戏付款')).toBeLessThan(orderedNames.indexOf('游戏内购买'))
  expect(orderedNames.indexOf('游戏内购买')).toBeLessThan(orderedNames.indexOf('电影'))
  expect(orderedNames.indexOf('电影')).toBeLessThan(orderedNames.indexOf('生活'))
  await page.locator('nav button').filter({ hasText: '总览' }).click()
  await page.getByRole('button', { name: /记录一笔/ }).click()
  await page.getByRole('button', { name: '选择支出账户', exact: true }).click()
  await page.getByRole('dialog', { name: '选择支出账户' }).getByRole('button', { name: '现金', exact: true }).click()
  await page.locator('[name="draft-form-source-amount"]').fill('10')
  await page.getByRole('button', { name: '选择标签', exact: true }).click()
  const picker = page.getByRole('dialog', { name: '选择标签', exact: true })
  const leaf = picker.locator('.tag').filter({ hasText: '游戏内购买' })
  const parent = picker.locator('.tag.inherited')
  await leaf.click()
  await expect(picker.locator('.tag.inherited')).toHaveCount(2)
  await picker.locator('.tag').filter({ hasText: '娱乐 › 电影' }).click()
  await leaf.click()
  await expect(picker.locator('.tag.inherited')).toHaveCount(1)
  await parent.click()
  await expect(picker.getByText('同时取消这些子标签', { exact: true })).toBeVisible()
  await picker.getByRole('button', { name: '保留选择' }).click()
  await picker.locator('.tag.inherited').dblclick()
  await expect(picker.locator('.tag.primaryTag')).toContainText('娱乐')
  await expect(picker.locator('.tag.primaryTag b')).toHaveText('主')
  await picker.locator('.tag.primaryTag').click()
  await expect(picker.locator('.tag.inherited')).toHaveCount(1)
  await picker.locator('.tag.inherited').click()
  await picker.getByRole('button', { name: '同时取消这些子标签' }).click()
  await expect(picker.locator('.tag.selected')).toHaveCount(0)
  await leaf.click()
  await picker.getByRole('button', { name: '确认', exact: true }).click()
  await page.getByRole('button', { name: '加入待提交列表' }).click()
  await page.getByRole('button', { name: '提交暂存', exact: true }).click()
  await expect(page.locator('.modal')).toHaveCount(0)
  await page.locator('nav button').filter({ hasText: '账目' }).click()
  await expect(page.locator('.transaction-list')).toContainText('继承：')
  await page.locator('.transaction-row-actions').getByRole('button', { name: /删除账目/ }).click()
  const deleteDialog = page.getByRole('dialog', { name: '删除这笔账目？' })
  await expect(deleteDialog).toContainText('新增一条资金流向相反的冲销记录')
  await deleteDialog.getByRole('button', { name: '取消', exact: true }).click()
  await expect(deleteDialog).not.toBeVisible()
  await page.locator('.transaction-row-actions').getByRole('button', { name: '标签', exact: true }).click()
  await expect(page.locator('.tag-selection .inherited')).toHaveCount(2)
  await page.getByRole('button', { name: '保存标签' }).click()
  await page.locator('.transaction-row-actions').getByRole('button', { name: '更正', exact: true }).click()
  await expect(page.locator('.tag-selection .inherited')).toHaveCount(2)
  await page.locator('[name="correction-form-source-amount"]').fill('12')
  await page.getByRole('button', { name: '保存更正' }).click()
  await expect(page.locator('.modal')).toHaveCount(0)
  await page.getByRole('button', { name: /^筛选/ }).click()
  await page.locator('[name="transaction-filters-tag-id"]').selectOption({ label: '娱乐' })
  await expect(page.locator('.transaction-list article')).toHaveCount(1)
  await page.locator('[name="transaction-filters-tag-mode"]').selectOption('direct')
  await expect(page.locator('.transaction-list article')).toHaveCount(0)
  await page.locator('nav button').filter({ hasText: '统计' }).click()
  await page.locator('[name="primary-grouping"]').selectOption('root')
  await expect(page.locator('.donut-layout')).toContainText('娱乐')
  await expect(page.locator('.donut-layout')).not.toContainText('游戏内购买')
  await page.locator('.donut-layout').getByRole('button', { name: '娱乐', exact: true }).click()
  await expect(page.locator('[name="transaction-filters-tag-mode"]')).toHaveValue('primary-root')
  await expect(page.locator('.transaction-list article')).toHaveCount(1)
  await page.locator('nav button').filter({ hasText: '标签' }).click()
  await page.getByRole('button', { name: '修改标签 游戏付款', exact: true }).click()
  await page.locator('[name="tag-edit-name"]').fill('游戏支付')
  await page.locator('[name="parent-edit-id"]').selectOption({ label: '生活' })
  await expect(page.locator('.modal')).toContainText('重新计算 2 条记录')
  await expect(page.locator('.hierarchy-warning')).toContainText('娱乐：-')
  await page.locator('[name="parent-edit-confirmed"]').check()
  await page.getByRole('button', { name: '保存修改', exact: true }).click()
  await expect(page.locator('.tag-management-list')).toContainText('游戏支付')
  await expect(page.locator('.tag-management-list')).toContainText('游戏内购买')
  await page.getByRole('button', { name: '删除标签 游戏支付', exact: true }).click()
  await expect(page.getByRole('button', { name: '确认删除', exact: true })).toBeDisabled()
  await page.locator('[name="child-disposition-mode"]').selectOption('promote')
  await page.getByRole('button', { name: '确认删除', exact: true }).click()
  await expect(page.locator('.tag-management-list')).toContainText('游戏内购买')
  await expect(page.locator('.tag-management-list')).not.toContainText('游戏支付')
  await expect(page.locator('.modal')).toHaveCount(0)
  const tagInput = await page.locator('[name="tag-name"]').boundingBox()
  expect(tagInput!.width).toBeGreaterThan(180)
  await page.locator('.tag-management-list').evaluate(async element => { await Promise.all(element.getAnimations({ subtree: true }).map(animation => animation.finished.catch(() => {}))) })
  await page.screenshot({ path: test.info().outputPath('subtag-management.png'), fullPage: true })
  expect(errors).toEqual([])
})

test('legacy unlock cancels safely, exports original ciphertext, upgrades and offers recovery migration', async ({ page }) => {
  const fixture = await seed(page, true)
  await unlock(page, fixture.name)
  const migration = page.getByRole('dialog', { name: '补充账目发生时间' })
  await expect(migration).toBeVisible()
  await migration.getByRole('button', { name: '暂后处理并锁定', exact: true }).click()
  await expect(page.locator('.app-shell')).toHaveCount(0)
  await page.getByRole('button', { name: '解锁账本', exact: true }).click()
  const download = page.waitForEvent('download')
  await migration.getByRole('button', { name: '导出升级前 .rwbl 备份' }).click()
  expect((await download).suggestedFilename()).toContain('v1升级前备份.rwbl')
  await migration.getByRole('button', { name: '确认时间并升级', exact: true }).click()
  await expect(page.locator('.welcome')).toBeVisible()
  await page.locator('nav button').filter({ hasText: '设置' }).click()
  await page.getByRole('button', { name: /备份/ }).click()
  await expect(page.getByRole('button', { name: '导出升级前备份' })).toBeVisible()
  await page.getByRole('button', { name: '恢复上一版本', exact: true }).click()
  await page.locator('[name="recovery-secret"]').fill('test-passphrase')
  await page.getByRole('button', { name: '验证并恢复', exact: true }).click()
  await expect(migration).toBeVisible()
  await migration.getByRole('button', { name: '确认时间并升级', exact: true }).click()
  await expect(migration).not.toBeVisible()
  await page.getByRole('button', { name: /退出/ }).click()
  await expect(page.locator('.app-shell')).not.toBeVisible()
  await unlock(page, fixture.name)
  await expect(page.locator('.welcome')).toBeVisible()
  await expect(migration).not.toBeVisible()
})

test('legacy file import uses the migration gate and temporary tag cancellation leaves no tag', async ({ page }) => {
  const fixture = await seed(page, true, false)
  await page.getByRole('button', { name: /导入账本/ }).click()
  await page.locator('input[type="file"]').setInputFiles({ name: 'legacy.rwbl', mimeType: 'application/json', buffer: Buffer.from(fixture.text) })
  await page.getByLabel('文件访问口令', { exact: true }).fill('test-passphrase')
  await page.getByRole('button', { name: /验证并导入/ }).click()
  const migration = page.getByRole('dialog', { name: '补充账目发生时间' })
  await expect(migration).toBeVisible()
  await migration.getByRole('button', { name: '确认时间并升级', exact: true }).click()
  await expect(page.locator('.ledger-card')).toContainText(fixture.name)
  await unlock(page, fixture.name)
  await page.getByRole('button', { name: /记录一笔/ }).click()
  await page.getByRole('button', { name: '选择标签', exact: true }).click()
  const picker = page.getByRole('dialog', { name: '选择标签', exact: true })
  await picker.locator('[name="pending-parent-id"]').selectOption({ label: '娱乐' })
  await picker.locator('[name="tag-picker-search"]').fill('取消的临时子标签')
  await picker.locator('[name="tag-picker-search"]').press('Enter')
  await expect(picker.locator('.tag')).toContainText(['收入', '出行', '饮食', '娱乐', '生活', '娱乐 › 取消的临时子标签'])
  await expect(picker.locator('.inherited')).toHaveCount(1)
  await picker.getByRole('button', { name: '取消', exact: true }).click()
  await page.getByRole('button', { name: '选择标签', exact: true }).click()
  await expect(picker).not.toContainText('取消的临时子标签')
})
